name: fluffychat
description: Game Store with Cinny Chat
publish_to: none
version: 1.2.4+10

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  animations: ^2.1.1
  async: ^2.11.0
  badges: ^3.1.2
  blurhash_dart: ^1.2.1
  chewie: ^1.13.0
  collection: ^1.18.0
  device_info_plus: ^12.3.0
  dio: ^5.0.0
  dynamic_color: ^1.8.1
  file_picker: ^10.3.7
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.0
  flutter_html: ^3.0.0
  flutter_inappwebview: ^6.1.5
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  go_router: ^17.0.0
  html: ^0.15.4
  http: ^1.6.0
  image: ^4.1.7
  image_picker: ^1.2.1
  intl: any
  just_audio: ^0.10.5
  linkify: ^5.0.0
  package_info_plus: ^8.3.1
  path: ^1.9.0
  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  provider: ^6.0.2
  punycode: ^1.0.0
  scroll_to_index: ^3.0.1
  share_plus: ^12.0.1
  shared_preferences: ^2.2.0
  slugify: ^2.0.0
  url_launcher: ^6.3.2
  video_player: ^2.10.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

import_sorter:
  ignored_files:
    - \/lib\/l10n

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/info-logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/
